version: '3.7'

services:
  server:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: nodemon start
    volumes:
      - ./back/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5100:5100"
    depends_on:
      - mongo
    env_file: ./back/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  client:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    env_file: ./front/.env   
    volumes:
      - ./front/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local